<!DOCTYPE html>
<html>
<head>
    <title>Raport obecności za okres: {{ $date_from }} - {{ $date_to }}</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            border-spacing: 0;
            margin-bottom: 1%;
            background: #fff;
        }

        table, th {
            border: 1px solid black;
            text-align: center;
            font-size: 11px;
            border-top: 2px solid;
            padding: 5px 12px;
            text-align: center;
            vertical-align: top;
            page-break-inside: avoid;
            background: #cde;
            padding: 5px;
        }

        .free_days_header {
            color: red;
            font-weight: bold;
        }

        .free_days {
            color: red;
        }

        .overtime_header {
            font-size: 11px;
            color: brown;
            font-weight: bold;
        }

        .overtime_header_week_days {
            font-size: 11px;
            color: darkred;
            font-weight: bold;
        }

        .overtime_header_weekend_days {
            font-size: 11px;
            color: orangered;
            font-weight: bold;
        }

        .overtime {
            font-size: 11px;
            color: brown;
        }

        .amount_free_days {
            text-align: right;
            font-size: 11px;
            color: red;
            font-weight: bold;
        }

        @page {
            header: page-header;
            footer: page-footer;
        }
    </style>
</head>
<body>

<htmlpageheader name="page-header">
    <div style="border-bottom: 1px solid #000000; font-weight: bold;  font-size: 10pt; text-align: center">
        @lang('Report for the period'): {{ $date_from }} - {{ $date_to }}
    </div>
</htmlpageheader>

<htmlpagefooter name="page-footer">
    <div style="border-top: 1px solid #000000; font-size: 10pt; text-align: center">
        @lang('date of generation'): <strong>{DATE j-m-Y}</strong><br>
        @lang('generated by'): <strong>{{ $generate_user }}</strong><br>
        @lang('page'): <strong>{PAGENO}/{nbpg}</strong>
    </div>
</htmlpagefooter>

@foreach ($report as $user)

    @if($is_admin or ($user_id==$user['user_id']))

        <table style="width:19cm;" autosize="1">
            <tr class="tr-naglowek">
                @if($is_admin)
                    <th>@lang('No.')</th>
                @endif
                <th width="2cm">@lang('Person')</th>
                <th width="14cm">{{ucfirst($string_month)}}</th>
            </tr>
            <tr>
                @if($is_admin)
                    <td rowspan="4" valign="middle">{{ $loop->iteration }}</td>
                @endif
                <td rowspan="4" valign="middle">{{ $user['first_name'] }}<br>{{ $user['last_name'] }}</td>
                <td valign="top" align="center">
                    @isset($user['months'][$int_month])
                        @isset($user['months'][$int_month]['timestamp'])
                            @include('pdf._partials.availability_work_times', ['user' => $user, 'int_month' => $int_month])
                        @endisset
                    @endisset
                    @isset($user['months'][$int_month]['free_days'])
                        <span class="free_days_header">@lang('Free days'): {{ count($user['months'][$int_month]['free_days']) }}</span>
                        <br>
                        @foreach($user['months'][$int_month]['free_days'] as $free_day)
                            <span class="free_days">{{ $free_day }}</span><br>
                        @endforeach
                    @endisset
                    @isset($user['months'][$int_month]['overtime_summary'])
                        <span class="overtime_header">@lang('overtime'): {{floor($user['months'][$int_month]['overtime_summary'] / 3600) . ':' .  ($user['months'][$int_month]['overtime_summary'] / 60) % 60}}h</span>
                        <br>
                    @endisset
                    @isset($user['months'][$int_month]['overtime_summary_week_days'])
                        <span class="overtime_header_week_days">@lang('Overtime week days'): {{floor($user['months'][$int_month]['overtime_summary_week_days'] / 3600) . ':' .  ($user['months'][$int_month]['overtime_summary_week_days'] / 60) % 60}}h</span>
                        <br>
                    @endisset
                    @isset($user['months'][$int_month]['overtime_summary_saturdays'])
                        <span class="overtime_header_weekend_days">@lang('Overtime saturdays'): {{floor($user['months'][$int_month]['overtime_summary_saturdays'] / 3600) . ':' .  ($user['months'][$int_month]['overtime_summary_saturdays'] / 60) % 60}}h</span>
                        <br>
                    @endisset
                    @isset($user['months'][$int_month]['overtime_summary_sundays'])
                        <span class="overtime_header_weekend_days">@lang('Overtime sundays'): {{floor($user['months'][$int_month]['overtime_summary_sundays'] / 3600) . ':' .  ($user['months'][$int_month]['overtime_summary_sundays'] / 60) % 60}}h</span>
                        <br>
                    @endisset
                    @isset($user['months'][$int_month]['overtime'])
                        @foreach($user['months'][$int_month]['overtime'] as $overtime)
                            <span class="overtime">{{ $overtime }}</span><br>
                        @endforeach
                    @endisset
                </td>
            </tr>
        </table>
        <span class="amount_free_days">{{$user['first_name']}}- @lang('free days in period'): {{ $user['amount_free_days'] }}</span>
        <br>
        <br>
    @else
    @endif
@endforeach
</body>
</html> 