swagger: '2.0'
info:
  title: Invoice filter
  description: Display available invoice filter
  version: "1.0.0"
# the domain of the service
host: localhost
# array of all schemes that your API supports
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

# will be prefixed to all paths
basePath: /
paths:
  /invoice-filters:
    get:
      summary: Display list of invoice filters
      description: |
        Displays list of available invoice filters.
      tags:
        - Invoice filter
      parameters:
        - name: selected_company_id
          in: query
          description: Id of company for which users are displayed
          required: true
          type: integer
      responses:
        200:
          description: Invoice filters list
          schema:
              $ref: "#/definitions/SuccessInvoiceFiltersIndexResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema:
              $ref: "#/definitions/ErrorResponse"

definitions:
  SuccessInvoiceFiltersIndexResponse:
    type: object

    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/InvoiceFilter"
      exec_time:
        type: number
        format: float
        description: API execution time

  InvoiceFilter:
    type: object
    properties:
      slug:
        type: string
        description: Invoice filter slug
      description:
        type: string
        description: Invoice filter description for Vat Payer

  ErrorResponse:
    type: object
    properties:
      code:
        type: string
        description: Error code.
      fields:
        type: array
        description: Error messages for each field. As keys you will get field names and as values you will get error messages for those fields
        items:
          type: string
      exec_time:
        type: number
        format: float
        description: API execution time
