swagger: "2.0"
info:
  title: Current packages
  description: This section describes buy, or update a module for company
  version: "1.0.0"

host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

basePath: /
paths:

  /modules:
    post:
      summary: Select package
      description: Select package for buying
      tags:
        - Modules
      parameters:
        - name: selected_company_id
          in: query
          description: Current company id
          required: true
          type: integer
        - name: days
          in: formData
          description: Days 0 (if change), 30, 365
          required: true
          type: integer
        - name: is_test
          in: formData
          description: 0 - no test, 1 - test
          required: true
          type: integer
        - name: currency
          in: formData
          description: currency PLN or EUR
          required: true
          type: string
        - name: mod_price_id
          in: formData
          description: ModPriceId
          required: true
          type: integer
        - name: checksum
          in: formData
          description: Checksum
          required: true
          type: string

      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/SaveSuccess"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema:
            $ref: "#/definitions/ErrorResponse"
        422:
          description: Validation error. As code you will get `general.validation_failed`
          schema:
            $ref: "#/definitions/ErrorResponse"
        409:
          description: Wrong checksum or checsum expired etc. As code you will get `package.data_consistency_error`
          schema:
            $ref: "#/definitions/ErrorResponse"


  /modules/current:
    get:
      summary: Get current extra modules
      description: Get current extra modules.
      tags:
        - Modules
      parameters:
        - name: selected_company_id
          in: query
          description: Current company id
          required: true
          type: integer
      responses:
        200:
          description: Modules
          schema:
            $ref: "#/definitions/CurrentResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema:
            $ref: "#/definitions/ErrorResponse"

  /modules/available:
    get:
      summary: Get available premium extra modules
      description: Get available premium extra modules.
      tags:
        - Modules
      parameters:
        - name: selected_company_id
          in: query
          description: Current company id
          required: true
          type: integer
      responses:
        200:
          description: Modules
          schema:
            $ref: "#/definitions/AvailableResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema:
            $ref: "#/definitions/ErrorResponse"

  /modules/{id}:
    delete:
      summary: Delete active module
      description: |
        Owner can delete active module (only if hasn`t got subscription).
      tags:
        - Modules
      parameters:
        - name: selected_company_id
          in: query
          description: Id of company for which error logs will be displayed
          required: true
          type: integer
        - name: id
          in: path
          description: Module id
          required: true
          type: number
      responses:
        204:
          description: Module was changed to default.
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: Reicept is not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
        422:
          description: Validation error. As code you will get `general.validation_failed` (if fields are not filled in valid way)
          schema:
            $ref: "#/definitions/ErrorResponse"

  /modules/limits:
    get:
      summary: Get current extra modules
      description: Get current extra modules.
      tags:
        - Modules
      parameters:
        - name: selected_company_id
          in: query
          description: Current company id
          required: true
          type: integer
      responses:
        200:
          description: Modules
          schema:
            $ref: "#/definitions/LimitsResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:

  SaveSuccess:
    type: object
    properties:
      data:
        type: object
        description: Transaction
        properties:
          id:
            type: number
            format: int
            description: Id
          created_at:
            type: string
            description: Date of company creation in `Y-m-d H:i:s` format
          updated_at:
            type: string
            description: Date of last compayny update in `Y-m-d H:i:s` format
          payments:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Payment"
      exec_time:
        type: number
        format: float
        description: API execution time

  Payment:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id
      transaction_id:
        type: integer
        description: Transaction id
      subscription_id:
        type: integer
        description: Subscription id
      price_total:
        type: integer
        description: Price total
      currency:
        type: integer
        description: PLN or EUR
      vat:
        type: integer
        description: VAT
      external_order_id:
        type: string
        description: Order id from payu
      status:
        type: string
        description: Status
      type:
        type: integer
        description: 0-simply, 1-card
      created_at:
        type: string
        description: Date of company creation in `Y-m-d H:i:s` format
      updated_at:
        type: string
        description: Date of last compayny update in `Y-m-d H:i:s` format

  CurrentResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/CompanyModule"
      exec_time:
        type: number
        format: float
        description: API execution time

  LimitsResponse:
    type: object
    properties:
      data:
        type: object
        additionalProperties:
          type: string
      exec_time:
        type: number
        format: float
        description: API execution time

  AvailableResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ModuleWithMods"
      exec_time:
        type: number
        format: float
        description: API execution time

  CompanyModule:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id
      company_id:
        type: number
        format: int
        description: Company id
      module_id:
        type: number
        format: int
        description: module id
      value:
        type: string
        description: Name
      package_id:
        type: number
        format: int
        description: package_id
      subscription_id:
        type: number
        format: int
        description: package_id
      has_active_subscription:
        type: boolean
        description: has_active_subscription
      expiration_date:
        type: string
        description: Date of expiration module in `Y-m-d H:i:s` format
      created_at:
        type: string
        description: Date of contractor creation in `Y-m-d H:i:s` format
      updated_at:
        type: string
        description: Date of last contractor update in `Y-m-d H:i:s` format
      module:
        description: Module
        schema:
          type: object
          properties:
            data:
              $ref: "#/definitions/Module"

  ModuleWithMods:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id
      name:
        type: string
        description: Name
      slug:
        type: string
        description: Slug
      description:
        type: string
        description: Description
      visible:
        type: boolean
        description: Show on list on page
      available:
        type: boolean
        description: Is availeble in this time
      mods:
        type: object
        properties:
          data:
            type: array
            items:
              $ref: "#/definitions/ModsWithModPrices"

  ModsWithModPrices:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id
      module_id:
        type: number
        format: int
        description: module id
      test:
        type: boolean
        description: Is test mod
      value:
        type: string
        description: Value
      error:
        type: string
        description: Error value `free_package_now_used`, `module_mod_currently_used`, `module_mod_currently_used_can_extend`, `unavailable_value`, `waiting_for_payment`
      mod_prices:
        type: object
        properties:
          data:
            type: array
            items:
              $ref: "#/definitions/ModPrices"

  ModPrices:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id
      module_mod_id:
        type: number
        format: int
        description: module mod id
      package_id:
        type: number
        format: int
        description: package id
      days:
        type: number
        format: int
        description: Days (0, 30, 365)
      default:
        type: boolean
        description: Is default price
      price:
        type: number
        format: int
        description: Price for renew in 'grosz'
      price_change:
        type: number
        format: int
        description: Price for change in 'grosz'
      currency:
        type: string
        description: PLN or EUR
      checksum:
        type: string
        description: checksum (renew) for send when this price is selected or null when is error
      checksum_change:
        type: string
        description: checksum (change) for send when this price is selected or null when is error
      created_at:
        type: string
        description: Date of contractor creation in `Y-m-d H:i:s` format
      updated_at:
        type: string
        description: Date of last contractor update in `Y-m-d H:i:s` format

  Module:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Id
      name:
        type: string
        description: Name
      slug:
        type: string
        description: Slug
      description:
        type: string
        description: Description
      visible:
        type: boolean
        description: Show on list on page
      available:
        type: boolean
        description: Is availeble in this time
      mods_count:
        type: number
        format: int
        description: Available mods count

  Success:
    type: object
    properties:
      code:
        type: string
        description: message
      data:
        type: object
        properties:
          success:
            type: boolean
      exec_time:
        type: number
        format: float
        description: API execution time

  ResourceNotFound:
    type: object
    properties:
      exec_time:
        type: number
        format: float
        description: API execution time
      code:
        type: string
        description: message

  ValidationError:
    type: object
    properties:
      exec_time:
        type: number
        format: float
        description: API execution time
      code:
        type: string
        description: message

  ErrorResponse:
    type: object
    properties:
      code:
        type: string
        description: Error code.
      fields:
        type: array
        description: Error messages for each field. As keys you will get field names and as values you will get error messages for those fields
        items:
          type: string
      exec_time:
        type: number
        format: float
        description: API execution time