swagger: '2.0'
info:
  title: Ticekt types
  description: Display available ticekt types
  version: "1.0.0"
# the domain of the service
host: localhost
# array of all schemes that your API supports
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json  

# will be prefixed to all paths
basePath: /
paths:
  /roles:
    get:
      summary: Display list of ticekt types
      description: |
        Displays list of available ticekt types.
      tags:
        - Ticekt types
      responses:
        200:
          description: Roles list
          schema: 
              $ref: "#/definitions/IndexResponse"
        401:
          description: User has no access to display this page. As code you will get `general.no_action_permission`
          schema: 
              $ref: "#/definitions/ErrorResponse"

definitions:
  IndexResponse:
    type: object

    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/Type"
      exec_time:
        type: number
        format: float
        description: API execution time
      
  Type:
    type: object
    properties:
      id:
        type: number
        format: int
        description: Type id
      name:   
        type: string
        description: Type name

  ErrorResponse:
    type: object
    properties:
      code:
        type: string
        description: Error code.
      fields:
        type: array
        description: Error messages for each field. As keys you will get field names and as values you will get error messages for those fields
        items: 
          type: string
      exec_time:
        type: number
        format: float 
        description: API execution time
