@startuml

left to right direction
title Add Interaction to Comment/Task///Document// \n

(Add Comment///Document//) as (Use)
(Select Interaction User/Group) as (SelectUser)

User --> (SelectUser)
User --> (Use)

@enduml